name = "example"
description = "Shiny new project"
version = "0.1.0-dev"

executables = ["example"]

[[depends-on]]
arduboy = "*"

[[pins]]
arduboy = { path = '..' }

[[actions]]
type = "post-build"
command = ["avr-objcopy", "-O", "ihex", "bin/example.elf", "bin/example.hex"]
